name: Comment On New Issues
on:
  issues:
    types: [opened]
jobs:
  commentOnNewIssues:
    name: Comment on new issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment on new issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Thank you for openning an issue, Canh will take care of it"