name: Notify Chatwork

on:
  pull_request:
    types: [opened]

jobs:
  notify_chatwork:
    runs-on: ubuntu-latest
    steps:
      - name: Open Pull Requests Chatwork Notifier
        uses: KeisukeKudo/open_pull-request_chatwork_notifier@v1
        with:
          chatwork-api-token: ${{ secrets.CHATWORK_API_TOKEN }}
          chatwork-room-id: ${{ secrets.CHATWORK_ROOM_ID }}